// 문구.js — 모든 글자. 키는 한국어. en 이 비면 ko 로 대체.
const 문구 = {
  시작:{ko:"시작",en:"Start"}, 이어하기:{ko:"이어하기",en:"Continue"},
  개집:{ko:"개집",en:"Kennel"}, 뽑기:{ko:"뽑기",en:"Adopt"}, 교배:{ko:"교배",en:"Breed"},
  설정:{ko:"설정",en:"Settings"}, 지도:{ko:"지도",en:"Map"}, 마당:{ko:"마당",en:"Yard"},
  건너뛰기:{ko:"건너뛰기",en:"Skip"}, 탭해서_계속:{ko:"눌러서 계속",en:"Tap to continue"},
  탄:{ko:"탄",en:"Stage"}, 양:{ko:"양",en:"Sheep"}, 마리:{ko:"마리",en:""},
  제한시간:{ko:"제한시간",en:"Time"}, 무제한:{ko:"무제한",en:"No limit"},
  별_클리어:{ko:"양 모으기",en:"Herd the sheep"}, 별_손실0:{ko:"한 마리도 안 잃기",en:"Lose none"},
  별_시간:{ko:"초 남기고 끝내기",en:"s left on the clock"},
  보스:{ko:"보스",en:"Boss"}, 여우:{ko:"여우",en:"Fox"}, 늑대:{ko:"늑대",en:"Wolf"}, 늑대대장:{ko:"늑대 대장",en:"Wolf chief"},
  계속:{ko:"계속",en:"Resume"}, 다시:{ko:"다시",en:"Retry"}, 다음:{ko:"다음",en:"Next"},
  일시정지:{ko:"일시정지",en:"Paused"}, 성공:{ko:"성공!",en:"Done!"}, 실패:{ko:"실패",en:"Failed"},
  시간초과:{ko:"시간 초과",en:"Time's up"}, 양_너무_잃음:{ko:"양을 너무 많이 잃었어요",en:"Too many sheep lost"},
  코인:{ko:"코인",en:"Coins"}, 뼈다귀:{ko:"뼈다귀",en:"Bones"},
  짖기:{ko:"짖기",en:"Bark"}, 호루라기:{ko:"호루라기",en:"Whistle"},
  튜토_이동:{ko:"화면을 눌러 개를 움직여요",en:"Tap to move the dog"},
  튜토_짖기:{ko:"짖으면 양이 도망가요",en:"Bark to push sheep"},
  튜토_분류:{ko:"양 색과 같은 우리에 넣어요",en:"Match sheep to pen color"},
  튜토_호루라기:{ko:"호루라기 뒤 늑대를 눌러요",en:"Whistle, then tap the wolf"},
  잃음:{ko:"잃음",en:"Lost"},
  레벨:{ko:"레벨",en:"Lv"}, 레벨업:{ko:"레벨업",en:"Level up"}, 간식:{ko:"간식",en:"Treat"},
  마당에_내보내기:{ko:"마당에 내보내기",en:"Send to yard"}, 마당에서_들이기:{ko:"개집에 들이기",en:"Bring in"},
  마당_꽉참:{ko:"마당은 5마리까지",en:"Yard holds 5"},
  속도:{ko:"속도",en:"Speed"}, 짖기범위:{ko:"짖기",en:"Bark"}, 양진정:{ko:"진정",en:"Calm"}, 늑대위협:{ko:"위협",en:"Guard"},
  기분:{ko:"기분",en:"Mood"},
  뽑기_비용:{ko:"뼈다귀 10개",en:"10 bones"}, 뼈다귀_부족:{ko:"뼈다귀가 모자라요",en:"Not enough bones"},
  코인_부족:{ko:"코인이 모자라요",en:"Not enough coins"},
  확률표:{ko:"확률",en:"Odds"}, 일반:{ko:"일반",en:"Common"}, 희귀:{ko:"희귀",en:"Rare"}, 전설:{ko:"전설",en:"Legend"},
  새_친구:{ko:"새 친구!",en:"New friend!"}, 중복:{ko:"이미 있어요 (경험 +50)",en:"Already have (XP +50)"},
  광고_뼈다귀:{ko:"광고 보고 뼈다귀 +1",en:"Watch ad: +1 bone"}, 광고_준비중:{ko:"광고 준비 중",en:"Ads coming soon"},
  광고_다봄:{ko:"오늘은 다 봤어요",en:"No more ads today"},
  교배_준비중:{ko:"30탄을 깨면 열려요",en:"Opens after stage 30"},
  출석:{ko:"출석 보상",en:"Daily gift"}, 일차:{ko:"일차",en:"Day"}, 받기:{ko:"받기",en:"Claim"},
  효과음:{ko:"효과음",en:"Sound"}, 배경음:{ko:"배경음",en:"Music"}, 진동:{ko:"진동",en:"Vibration"},
  언어:{ko:"언어",en:"Language"}, 인트로_다시:{ko:"이야기 다시 보기",en:"Replay intro"},
  초기화:{ko:"데이터 초기화",en:"Reset data"}, 초기화_확인:{ko:"정말 지울까요?",en:"Delete everything?"},
  개인정보:{ko:"개인정보처리방침",en:"Privacy policy"}, 켜짐:{ko:"켜짐",en:"On"}, 꺼짐:{ko:"꺼짐",en:"Off"},
  돌아온_양:{ko:"돌아온 양",en:"Sheep home"},
  준비중:{ko:"준비 중",en:"Coming soon"}, 다음_목장:{ko:"다음 목장을 준비하고 있어요",en:"The next farm is on its way"},
  닫기:{ko:"닫기",en:"Close"}, 예:{ko:"예",en:"Yes"}, 아니오:{ko:"아니오",en:"No"},
  잠김:{ko:"잠김",en:"Locked"}, 쓰다듬기:{ko:"쓰다듬기",en:"Pet"}, 공:{ko:"공",en:"Ball"},
  오늘_다함:{ko:"오늘은 충분히 놀았어요",en:"Enough play for today"},
  보더콜리:{ko:"보더콜리",en:"Border Collie"}, 코기:{ko:"코기",en:"Corgi"}, 골든리트리버:{ko:"골든리트리버",en:"Golden Retriever"},
  진도견:{ko:"진도견",en:"Jindo"}, 삽살개:{ko:"삽살개",en:"Sapsali"}, 저먼셰퍼드:{ko:"저먼셰퍼드",en:"German Shepherd"},
  소개_보더콜리:{ko:"뭐든 잘하는 양치기",en:"The all-round herder"},
  소개_코기:{ko:"느리지만 양이 안 놀라요",en:"Slow, but sheep stay calm"},
  소개_골든리트리버:{ko:"짖기가 넓고 자주",en:"Big, frequent bark"},
  소개_진도견:{ko:"제일 빠른 한국 개",en:"Korea's fastest"},
  소개_삽살개:{ko:"귀신도 쫓는 한국 개",en:"Chases ghosts and wolves"},
  소개_저먼셰퍼드:{ko:"늑대가 못 오게 지켜요",en:"Wolves keep away"},
  털색_기본:{ko:"기본",en:"Classic"}, 털색_어둠:{ko:"진한 털",en:"Dark coat"}, 털색_밝음:{ko:"밝은 털",en:"Light coat"},
  미션:{ko:"미션",en:"Tasks"}, 오프라인_제목:{ko:"자는 동안 모았어요",en:"Collected while you were away"}, 이름:{ko:"이름",en:"Name"}, 이름_묻기:{ko:"이 개의 이름은? (8자까지)",en:"Name this dog (8 letters)"},
  탄_성공_컷:{ko:"양들이 돌아왔어요",en:"The sheep are home"},
};
function 글(키){ const 항=문구[키]; if(!항) return 키; const l=(typeof 저장!=="undefined"&&저장.자료)?저장.자료.언어:"ko"; return 항[l]||항.ko; }
