// 문구.js — 모든 글자. 키는 한국어. en 이 비면 ko 로 대체.
const 문구 = {
  시작:{ko:"시작",en:"Start"}, 이어하기:{ko:"이어하기",en:"Continue"},
  개집:{ko:"내 강아지",en:"My Dogs"}, 뽑기:{ko:"뽑기",en:"Adopt"}, 교배:{ko:"교배",en:"Breed"},
  설정:{ko:"설정",en:"Settings"}, 지도:{ko:"지도",en:"Map"}, 마당:{ko:"마당",en:"Yard"},
  건너뛰기:{ko:"건너뛰기",en:"Skip"}, 탭해서_계속:{ko:"눌러서 계속",en:"Tap to continue"},
  탄:{ko:"탄",en:"Stage"}, 양:{ko:"양",en:"Sheep"}, 마리:{ko:"마리",en:""},
  제한시간:{ko:"제한시간",en:"Time"}, 무제한:{ko:"무제한",en:"No limit"},
  별_클리어:{ko:"양 모으기",en:"Herd the sheep"}, 별_손실0:{ko:"한 마리도 안 잃기",en:"Lose none"},
  별_시간:{ko:"초 남기고 끝내기",en:"s left on the clock"},
  보스:{ko:"보스",en:"Boss"}, 여우:{ko:"여우",en:"Fox"}, 늑대:{ko:"늑대",en:"Wolf"}, 늑대대장:{ko:"늑대 대장",en:"Wolf chief"},
  계속:{ko:"계속",en:"Resume"}, 다시:{ko:"다시",en:"Retry"}, 다음:{ko:"다음",en:"Next"},
  일시정지:{ko:"일시정지",en:"Paused"}, 성공:{ko:"성공!",en:"Done!"}, 실패:{ko:"실패",en:"Failed"},
  시간초과:{ko:"시간 초과",en:"Time's up"}, 양_너무_잃음:{ko:"양을 너무 많이 잃었어요",en:"Too many sheep lost"},
  코인:{ko:"코인",en:"Coins"}, 뼈다귀:{ko:"뼈다귀",en:"Bones"},
  짖기:{ko:"짖기",en:"Bark"}, 호루라기:{ko:"호루라기",en:"Whistle"},
  튜토_이동:{ko:"화면을 눌러 개를 움직여요",en:"Tap to move the dog"},
  튜토_짖기:{ko:"짖으면 양이 도망가요",en:"Bark to push sheep"},
  튜토_분류:{ko:"양 색과 같은 우리에 넣어요",en:"Match sheep to pen color"},
  튜토_호루라기:{ko:"호루라기를 불면 늑대가 도망가요",en:"Blow the whistle to chase wolves away"},
  잃음:{ko:"잃음",en:"Lost"},
  레벨:{ko:"레벨",en:"Lv"}, 레벨업:{ko:"레벨업",en:"Level up"}, 간식:{ko:"간식",en:"Treat"},
  마당에_내보내기:{ko:"마당에 내보내기",en:"Send to yard"}, 마당에서_들이기:{ko:"마당에서 들이기",en:"Bring in"},
  마당_꽉참:{ko:"마당은 5마리까지",en:"Yard holds 5"},
  속도:{ko:"속도",en:"Speed"}, 짖기범위:{ko:"짖기",en:"Bark"}, 양진정:{ko:"진정",en:"Calm"}, 늑대위협:{ko:"위협",en:"Guard"},
  기분:{ko:"기분",en:"Mood"},
  뽑기_비용:{ko:"뼈다귀 10개",en:"10 bones"}, 뼈다귀_부족:{ko:"뼈다귀가 모자라요",en:"Not enough bones"},
  코인_부족:{ko:"코인이 모자라요",en:"Not enough coins"},
  확률표:{ko:"확률",en:"Odds"}, 일반:{ko:"일반",en:"Common"}, 희귀:{ko:"희귀",en:"Rare"}, 전설:{ko:"전설",en:"Legend"},
  새_친구:{ko:"새 친구!",en:"New friend!"}, 중복:{ko:"이미 있어요 (경험 +50)",en:"Already have (XP +50)"},
  광고_뼈다귀:{ko:"광고 보고 뼈다귀 +1",en:"Watch ad: +1 bone"}, 광고_준비중:{ko:"광고 준비 중",en:"Ads coming soon"},
  광고_다봄:{ko:"오늘은 다 봤어요",en:"No more ads today"},
  교배_준비중:{ko:"30탄을 깨면 열려요",en:"Opens after stage 30"},
  출석:{ko:"출석 보상",en:"Daily gift"}, 일차:{ko:"일차",en:"Day"}, 받기:{ko:"받기",en:"Claim"},
  효과음:{ko:"효과음",en:"Sound"}, 배경음:{ko:"배경음",en:"Music"}, 진동:{ko:"진동",en:"Vibration"},
  언어:{ko:"언어",en:"Language"}, 인트로_다시:{ko:"이야기 다시 보기",en:"Replay intro"},
  초기화:{ko:"데이터 초기화",en:"Reset data"}, 초기화_확인:{ko:"정말 지울까요?",en:"Delete everything?"},
  개인정보:{ko:"개인정보처리방침",en:"Privacy policy"}, 켜짐:{ko:"켜짐",en:"On"}, 꺼짐:{ko:"꺼짐",en:"Off"},
  돌아온_양:{ko:"돌아온 양",en:"Sheep home"},
  준비중:{ko:"준비 중",en:"Coming soon"}, 다음_목장:{ko:"다음 목장을 준비하고 있어요",en:"The next farm is on its way"},
  숨은능력:{ko:"숨은 능력",en:"Hidden gift"}, 숨은_아직:{ko:"？？？",en:"？？？"},
  숨은_멀리:{ko:"멀리 짖기",en:"Far bark"}, 숨은_느긋:{ko:"느긋한 눈",en:"Calm eyes"},
  숨은_쉼없이:{ko:"쉼 없이",en:"Tireless"}, 숨은_바람:{ko:"바람",en:"Wind"},
  숨은_쫓기:{ko:"늑대 쫓기",en:"Wolf chaser"}, 숨은_든든:{ko:"든든함",en:"Steadfast"},
  숨은_열림:{ko:"숨은 능력이 깨어났어요!",en:"A hidden gift awakened!"},
  한번더_나가기:{ko:"한 번 더 누르면 나가요",en:"Press back again to exit"},
  닫기:{ko:"닫기",en:"Close"}, 예:{ko:"예",en:"Yes"}, 아니오:{ko:"아니오",en:"No"},
  잠김:{ko:"잠김",en:"Locked"}, 쓰다듬기:{ko:"쓰다듬기",en:"Pet"}, 공:{ko:"공",en:"Ball"}, 밥:{ko:"밥",en:"Feed"}, 배불러:{ko:"배불러요",en:"Not hungry"},
  집사기:{ko:"집 사기",en:"House"}, 집가게:{ko:"강아지 집 가게",en:"Dog house shop"}, 사기:{ko:"사기",en:"Buy"},
  집_생김:{ko:"강아지 집이 생겼어요!",en:"The dog house is ready!"},
  집_바꾸기:{ko:"집 바꾸기",en:"Change house"}, 집_쓰기:{ko:"쓰기",en:"Use"}, 집_가짐:{ko:"내 집",en:"Owned"}, 집_바꿈:{ko:"집을 바꿨어요!",en:"House changed!"},
  집안:{ko:"집 안",en:"Inside"}, 집안_마당:{ko:"← 마당",en:"← Yard"}, 집안_가게:{ko:"꾸미기 가게",en:"Decor shop"},
  집안_놓음:{ko:"놓았어요!",en:"Placed!"}, 집안_빔:{ko:"강아지들은 마당에서 놀아요",en:"The dogs are out in the yard"},
  집안_잠:{ko:"쿨쿨 자고 있어요",en:"Sleeping soundly"}, 쿨쿨:{ko:"쿨쿨…",en:"Zzz…"}, 집안_눌러:{ko:"집을 누르면 안에 들어가요",en:"Tap the house to go inside"},
  뼈_이어하기:{ko:"🦴 10개로 이어하기",en:"Continue for 🦴10"},
  놀이시간:{ko:"놀이 시간",en:"Play time"}, 놀이_끄기:{ko:"끄기",en:"Off"}, 놀이_분:{ko:"분",en:" min"}, 놀이_1시간:{ko:"1시간",en:"1 hour"},
  놀이끝_1:{ko:"오늘 놀이 시간 끝~",en:"Play time is over for today~"}, 놀이끝_2:{ko:"강아지들 잘 시간이에요 💤",en:"Time for the dogs to sleep 💤"},
  어른확인:{ko:"어른 확인",en:"Grown-ups only"}, 어른_안내:{ko:"어른이 풀어 주세요",en:"Ask a grown-up"}, 놀이_10분더:{ko:"10분 더",en:"10 more min"}, 놀이_오늘끝:{ko:"오늘 끝",en:"Done for today"},
  놀이_내일:{ko:"내일 또 만나요!",en:"See you tomorrow!"}, 어른_틀림:{ko:"다시 해 보세요",en:"Try again"}, 놀이_고르기:{ko:"놀이 시간 고르기",en:"Choose play time"},
  비_집없음:{ko:"비가 와요! 집이 있으면 비를 피해요",en:"It's raining! A house keeps dogs dry"},
  수의사:{ko:"수의사 선생님",en:"Vet"}, 다나았어요:{ko:"다 나았어요!",en:"All better!"}, 배고파:{ko:"배고파요",en:"Hungry"},
  오늘_다함:{ko:"오늘은 충분히 놀았어요",en:"Enough play for today"},
  보더콜리:{ko:"보더콜리",en:"Border Collie"}, 코기:{ko:"코기",en:"Corgi"}, 골든리트리버:{ko:"골든리트리버",en:"Golden Retriever"},
  진도견:{ko:"진도견",en:"Jindo"}, 삽살개:{ko:"삽살개",en:"Sapsali"}, 저먼셰퍼드:{ko:"저먼셰퍼드",en:"German Shepherd"},
  소개_보더콜리:{ko:"뭐든 잘하는 양치기",en:"The all-round herder"},
  소개_코기:{ko:"느리지만 양이 안 놀라요",en:"Slow, but sheep stay calm"},
  소개_골든리트리버:{ko:"짖기가 넓고 자주",en:"Big, frequent bark"},
  소개_진도견:{ko:"제일 빠른 한국 개",en:"Korea's fastest"},
  소개_삽살개:{ko:"귀신도 쫓는 한국 개",en:"Chases ghosts and wolves"},
  소개_저먼셰퍼드:{ko:"늑대가 못 오게 지켜요",en:"Wolves keep away"},
  털색_기본:{ko:"기본",en:"Classic"}, 털색_어둠:{ko:"진한 털",en:"Dark coat"}, 털색_밝음:{ko:"밝은 털",en:"Light coat"},
  대형_흩어짐:{ko:"흩어짐",en:"Loose"}, 대형_삼각:{ko:"삼각",en:"Wedge"}, 대형_사각:{ko:"사각",en:"Box"}, 대형_한줄:{ko:"한줄",en:"Line"},
  대회:{ko:"대회",en:"Trial"}, 대회_설명:{ko:"양을 자리에 맞춰 세우세요",en:"Line the sheep up on the marks"},
  대회_성공:{ko:"모양 완성!",en:"Shape complete!"}, 대회_점수:{ko:"점수",en:"Score"}, 대회_상대:{ko:"목장주 기록",en:"Rancher's record"},
  대회_이김:{ko:"이겼어요!",en:"You win!"}, 대회_짐:{ko:"아깝다",en:"So close"}, 대회_최고:{ko:"내 최고",en:"Best"},
  대회_잠김:{ko:"30탄을 깨면 열려요",en:"Clear stage 30 to unlock"},
  훈장:{ko:"훈장",en:"Medals"}, 목욕:{ko:"목욕",en:"Bath"}, 목욕시킴:{ko:"뽀송뽀송해졌어요",en:"All dry and fluffy"},
  성격:{ko:"성격",en:"Personality"},
  성격_활발:{ko:"활발",en:"Lively"}, 성격_겁많음:{ko:"겁많음",en:"Timid"}, 성격_느긋:{ko:"느긋",en:"Easy-going"},
  성격_장난꾸러기:{ko:"장난꾸러기",en:"Playful"}, 성격_차분:{ko:"차분",en:"Calm"},
  미션:{ko:"미션",en:"Tasks"}, 오프라인_제목:{ko:"자는 동안 모았어요",en:"Collected while you were away"}, 이름:{ko:"이름",en:"Name"}, 이름_묻기:{ko:"이 개의 이름은? (8자까지)",en:"Name this dog (8 letters)"},
  기다렸어요:{ko:"집 앞에서 기다리고 있었어요",en:"They were waiting by the house"},
  많이_기다렸어요:{ko:"많이 기다렸어요! 달려옵니다",en:"They waited a long time — here they come!"},
  쓰담_안내:{ko:"손가락으로 문질러 주세요",en:"Rub with your finger"},
  산책:{ko:"산책",en:"Walk"}, 걸음:{ko:"걸음",en:"steps"},
  산책_안내:{ko:"폰을 들고 걸으면 같이 걸어요",en:"Hold your phone and walk together"},
  산책_센서없음:{ko:"이 기기는 걸음을 셀 수 없어요",en:"This device can't count steps"},
  산책_다했어요:{ko:"오늘 산책은 여기까지예요",en:"That's enough walking for today"},
  진짜산책:{ko:"진짜 산책 🚶",en:"Real Walk 🚶"},
  진짜산책_목표:{ko:"폰을 들고 300걸음 걸어요",en:"Walk 300 steps holding your phone"},
  진짜산책_보상:{ko:"다 걸으면 🦴 간식 + 코인 10",en:"Finish for a 🦴 treat + 10 coins"},
  진짜산책_안전1:{ko:"엄마·아빠랑 같이 걸어요!",en:"Walk with Mom or Dad!"},
  진짜산책_안전2:{ko:"걸을 땐 앞을 보세요 👀",en:"Look ahead while walking 👀"},
  진짜산책_켜둠:{ko:"앱을 켜 둔 동안만 걸음을 세요",en:"Steps count only while the app is open"},
  진짜산책_시작:{ko:"출발!",en:"Let's go!"},
  진짜산책_멈춤:{ko:"잠깐 멈췄어요",en:"Paused"},
  진짜산책_뒤에선:{ko:"앱을 안 보는 동안은 걸음을 못 세요",en:"Steps aren't counted while the app is hidden"},
  진짜산책_완료:{ko:"산책 끝! ♥",en:"Walk done! ♥"},
  진짜산책_간식:{ko:"간식을 받았어요",en:"Got a treat"},
  진짜산책_오늘다:{ko:"오늘 선물은 다 받았어요",en:"All of today's gifts received"},
  진짜산책_또:{ko:"한 번 더",en:"Again"},
  진짜산책_구경:{ko:"화면 속에서 같이 걸어요",en:"Walking together on screen"},
  AR산책:{ko:"AR 산책 📷",en:"AR Walk 📷"}, AR쉼:{ko:"쉬는 시간이에요 🐕💤",en:"Rest time 🐕💤"},
  공_던지는법:{ko:"화면을 꾹 눌렀다 떼면 던져요",en:"Press, hold, then let go to throw"}, 처음_공:{ko:"꾹 눌렀다 떼면 공을 던져요!",en:"Hold, then let go to throw!"}, 처음_간식:{ko:"냠냠! 간식을 줬어요",en:"Yum! You gave a treat"},
  띵동_1:{ko:"누가 왔나 봐요. 문을 열어 볼까요?",en:"Someone's at the door. Open it?"},
  띵동_2:{ko:"문 앞에 상자가 놓여 있어요.",en:"There's a box at the door."},
  띵동_3:{ko:"안에 강아지가 혼자 있었어요.",en:"A puppy was inside, all alone."},
  띵동_4:{ko:"같이 갈래?",en:"Want to come with me?"},
  오늘_남음:{ko:"오늘 남은 횟수",en:"Left today"},
  이름_지어주기:{ko:"이름 지어 주기",en:"Give a name"},
  쓰담_처음안내:{ko:"꾹 누른 채 문지르면 쓰다듬기 · 가만히 꾹 누르면 놀이",en:"Hold & rub to pet · Hold still to play"},
  부르기_안내:{ko:"땅을 톡 누르면 강아지가 와요",en:"Tap the ground to call your dog"},
  응가_안내:{ko:"톡! 치우기",en:"Tap to clean"}, 처음_응가:{ko:"깨끗해졌어요! 응가를 치우면 코인이 생겨요",en:"All clean! Cleaning up earns coins"},
  늑대_조심:{ko:"조심! 늑대!",en:"Watch out! Wolf!"}, 여우_조심:{ko:"조심! 여우!",en:"Watch out! Fox!"},
  터그:{ko:"터그",en:"Tug"}, 터그_안내:{ko:"위아래로 힘껏 당겨요!",en:"Pull up and down hard!"}, 터그_이김:{ko:"이겼다!",en:"You won!"},
  응가_치우면_코인:{ko:"응가를 치우면 코인이 생겨요",en:"Clean up poop to earn coins"},
  비밀코드:{ko:"비밀 코드",en:"Secret code"}, 코드_확인:{ko:"확인",en:"OK"}, 코드_다름:{ko:"코드가 달라요",en:"That code doesn't match"},
  코드_이미:{ko:"이미 받았어요",en:"Already claimed"}, 코드_특전:{ko:"특전 받았어요! 🦴",en:"Bonus received! 🦴"},
  어디에_둘까요:{ko:"어디에 밥을 둘까요?",en:"Where should the food go?"},
  멀리_던지기:{ko:"꾹 누를수록 멀리 날아가요",en:"Hold longer to throw farther"},
  꾹_눌러보기:{ko:"강아지를 꾹 누르면 가까이 와요",en:"Press and hold a dog to bring it close"},
  제목_양몰이:{ko:"양몰이",en:"Sheepdog"}, 제목_달빛목장:{ko:"달빛목장",en:"Moonlight Farm"},
  탭해서_시작:{ko:"탭해서 시작",en:"Tap to start"}, 띵동소리:{ko:"띵동",en:"Ding-dong"},
  확률_첫세번:{ko:"처음 세 번은 없는 것만 나와요",en:"First 3 pulls: only ones you don't have"},
  눌러서_이름:{ko:"눌러서 이름 바꾸기",en:"Tap to rename"},
  탄_성공_컷:{ko:"양들이 돌아왔어요",en:"The sheep are home"},
};
function 글(키){ const 항=문구[키]; if(!항) return 키; const l=(typeof 저장!=="undefined"&&저장.자료)?저장.자료.언어:"ko"; return 항[l]||항.ko; }
