#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""pdf300.com 도구별 SEO 랜딩페이지 데이터.

왜 필요한가: 지금 도구 24개가 index.html 한 장에 해시(#merge)로만 있어서
검색엔진이 'merge pdf' 같은 검색어에 우리를 못 걸어준다. 경쟁사(iLovePDF·Smallpdf)는
도구마다 독립 URL을 갖고 있고 그게 유입의 대부분이다.

⚠️ 얄팍한 도어웨이 페이지는 구글이 벌준다. 그래서 각 페이지에 실제 내용
(무엇을·어떻게 3단계·왜 우리·FAQ 2개)을 넣는다.
"""

# slug, h1/title, meta description, 앱 앵커, 본문 조각
TOOLS = [
    dict(slug="merge-pdf", anchor="#merge",
         title="Merge PDF — Combine PDFs in your browser, free",
         h1="Merge PDF files",
         desc="Combine several PDFs into one file. Runs in your browser — your files are never uploaded. No sign-up, no watermark.",
         what="Put two or more PDFs together in the order you choose, and download one merged file.",
         steps=["Drop your PDFs in (or click to browse).",
                "Drag the ▲▼ buttons to set the order.",
                "Press Merge & download."],
         faq=[("Is there a file size limit?",
               "No. Merging happens on your own machine, so the limit is your device's memory, not our server."),
              ("Do my files get uploaded?",
               "No. The merge tool runs entirely in your browser. Nothing leaves your computer.")]),
    dict(slug="split-pdf", anchor="#split",
         title="Split PDF — Extract pages or split by range, free",
         h1="Split a PDF",
         desc="Split a PDF by page range, into single pages, or into fixed-size groups. Browser-based, no upload, no sign-up.",
         what="Cut one PDF into several files — by a range like 1-3, 5, 7-10, one file per page, or every N pages.",
         steps=["Choose one PDF.", "Pick a split mode and range.", "Download the pieces as a ZIP."],
         faq=[("Can I pull out just one page?",
               "Yes. Use the range mode and enter a single page number."),
              ("Where does the splitting happen?",
               "In your browser. The file never reaches our server.")]),
    dict(slug="compress-pdf", anchor="#compress",
         title="Compress PDF — Reduce PDF file size, free",
         h1="Compress a PDF",
         desc="Make a PDF smaller in your browser. Choose how hard to compress. No upload for the browser mode, no watermark.",
         what="Re-encode each page as an image at a lower resolution so the file gets much smaller.",
         steps=["Choose a PDF.", "Pick a compression level.", "Press Compress and download."],
         faq=[("Will the text still be selectable?",
               "No. This mode redraws pages as images, so text search is lost. Use it when file size matters more."),
              ("I need an exact size, like under 300 KB.",
               "Use our compress-to-target-size tool — it finds the highest quality that fits your limit.")]),
    dict(slug="compress-pdf-to-size", anchor="/target-size",
         title="Compress PDF to an exact size (KB) — free",
         h1="Compress a PDF to an exact target size",
         desc="Set a target in KB and get a PDF that fits under it. Built for tender portals and upload limits that reject anything larger.",
         what="You tell it the maximum size, it searches for the highest quality that stays under your limit.",
         steps=["Choose a PDF.", "Type your target size in KB.", "Download the result."],
         faq=[("Why would I need this?",
               "Government and tender portals often reject files over a fixed size. Guessing compression levels wastes time; this hits the number."),
              ("Is it exact?",
               "It lands at or under your target. It will not go over.")]),
    dict(slug="jpg-to-pdf", anchor="#img2pdf",
         title="JPG to PDF — Convert images to PDF, free",
         h1="Convert images to PDF",
         desc="Turn JPG and PNG images into a single PDF. Runs in your browser, no upload, no watermark, no sign-up.",
         what="Bundle photos or scans into one PDF, with the page size and margins you choose.",
         steps=["Drop your images in.", "Choose page size, orientation and margin.", "Press Create PDF."],
         faq=[("Can I set the order?", "Yes — reorder the images before you build the PDF."),
              ("Are my photos uploaded?", "No. Everything happens on your device.")]),
    dict(slug="pdf-to-jpg", anchor="#pdf2img",
         title="PDF to JPG — Export PDF pages as images, free",
         h1="Convert PDF pages to images",
         desc="Export each page of a PDF as PNG, JPG or WebP at the resolution you pick. Browser-based, nothing uploaded.",
         what="Render every page to an image file and download them together as a ZIP.",
         steps=["Choose a PDF.", "Pick format and resolution.", "Download the ZIP."],
         faq=[("What resolution should I use?",
               "150 DPI is fine for screen. Use 300 DPI if the image will be printed."),
              ("Is there a page limit?", "No fixed limit — it depends on your device's memory.")]),
    dict(slug="pdf-to-text", anchor="#pdf2txt",
         title="PDF to text — Extract text from a PDF, free",
         h1="Extract the text from a PDF",
         desc="Pull the body text out of a PDF and save it as .txt. Runs in your browser. For scanned PDFs, use OCR instead.",
         what="Read the text layer of a PDF and give it back as plain text you can copy or download.",
         steps=["Choose a PDF.", "The text appears immediately.", "Copy it or download the .txt."],
         faq=[("Nothing came out — why?",
               "Your PDF is probably a scan, which has no text layer. Run OCR on it first."),
              ("Does formatting survive?", "No. You get plain text, not layout.")]),
    dict(slug="ocr-pdf", anchor="#srv-ocr",
         title="OCR a PDF — Read text from scanned PDFs, free",
         h1="OCR: read text from a scanned PDF",
         desc="Recognise characters in scanned or image-only PDFs, in English, Korean, Japanese or Chinese. Free while in beta.",
         what="Turns a picture of a document into text you can search, copy and paste.",
         steps=["Choose a scanned PDF.", "Pick the language.", "Copy the recognised text or download it."],
         faq=[("Which languages?", "English, Korean, Japanese and Chinese (Simplified)."),
              ("Does this one upload my file?",
               "Yes — OCR is too heavy for a browser, so it runs on our server. The file is processed and returned, not kept.")]),
    dict(slug="rotate-pdf", anchor="#organize",
         title="Rotate PDF — Fix page orientation, free",
         h1="Rotate and reorder PDF pages",
         desc="Rotate pages, drop the ones you don't want, and change page order. Browser-based, no upload, no sign-up.",
         what="See every page as a thumbnail, then rotate, exclude or reorder before saving.",
         steps=["Choose a PDF.", "Rotate or exclude pages in the preview.", "Save and download."],
         faq=[("Can I rotate only one page?", "Yes. Each page has its own rotate buttons."),
              ("Can I delete pages here?", "Yes — exclude a page and it won't be in the saved file.")]),
    dict(slug="crop-pdf", anchor="#crop",
         title="Crop PDF — Trim margins from every page, free",
         h1="Crop the margins of a PDF",
         desc="Trim the same margin from every page in millimetres. Runs in your browser, nothing uploaded.",
         what="Cut white space off the top, bottom, left and right of all pages at once.",
         steps=["Choose a PDF.", "Enter the margins in mm.", "Press Crop and download."],
         faq=[("Is content deleted?", "No — cropping changes the visible page box, it doesn't erase objects."),
              ("Can I crop one page differently?", "Not in this tool — it applies the same crop to every page.")]),
    dict(slug="watermark-pdf", anchor="#watermark",
         title="Add a watermark to a PDF — free, no sign-up",
         h1="Add a text watermark to a PDF",
         desc="Stamp text like DRAFT or CONFIDENTIAL across every page. Choose size, angle, colour and opacity.",
         what="Draw your text diagonally across all pages at the transparency you choose.",
         steps=["Choose a PDF.", "Type your text and set size, angle and opacity.", "Download the watermarked file."],
         faq=[("Do you add your own watermark?", "Never. Nothing we produce carries our branding."),
              ("Can I use Korean text?", "Yes — a Korean font is embedded automatically when needed.")]),
    dict(slug="add-page-numbers-pdf", anchor="#numbers",
         title="Add page numbers to a PDF — free",
         h1="Add page numbers to a PDF",
         desc="Insert page numbers at the position and format you choose. Browser-based, no upload, no watermark.",
         what="Put numbers on every page — bottom centre, top right, and formats like 'Page 1 of 20'.",
         steps=["Choose a PDF.", "Pick position, format, size and start number.", "Download."],
         faq=[("Can I start from a number other than 1?", "Yes — set the start number."),
              ("Can I skip the cover page?", "Start numbering from the page you want by setting the start number accordingly.")]),
    dict(slug="sign-pdf", anchor="#sign",
         title="Sign a PDF — Place a signature or stamp image, free",
         h1="Sign a PDF with an image",
         desc="Drop a signature or stamp PNG onto any page, at any position and size. Runs in your browser — your document never leaves it.",
         what="Place a transparent PNG of your signature or company stamp exactly where you want it.",
         steps=["Choose a PDF.", "Upload your signature image.", "Click the preview where it should go, then save."],
         faq=[("Is this a legally binding e-signature?",
               "No. This places an image of a signature. It is not a certificate-based digital signature."),
              ("Where does my document go?", "Nowhere. This tool runs entirely in your browser.")]),
    dict(slug="redact-pdf", anchor="#redact",
         title="Redact a PDF — Black out private areas, free",
         h1="Redact parts of a PDF",
         desc="Cover private areas with permanent black boxes, in your browser. Nothing is uploaded.",
         what="Drag rectangles over anything you want hidden; the boxes are burned into the saved file.",
         steps=["Choose a PDF.", "Drag over the areas to hide.", "Save and download."],
         faq=[("Can the hidden text be recovered?",
               "The box is drawn permanently into the page. For maximum safety, also run the result through our compress tool, which rasterises the page."),
              ("Does this upload my file?", "No.")]),
    dict(slug="unlock-pdf", anchor="#srv-unlock",
         title="Unlock a PDF — Remove a known password, free",
         h1="Remove the password from a PDF",
         desc="Strip the password from a PDF you already know the password for. Free while in beta.",
         what="Takes an encrypted PDF plus its password and returns the same file without encryption.",
         steps=["Choose the encrypted PDF.", "Enter its password.", "Download the unlocked file."],
         faq=[("Can it crack a password I don't know?",
               "No, and we won't help with that. You must supply the correct password."),
              ("Is my file kept?", "No. It is processed and returned, not stored.")]),
    dict(slug="protect-pdf", anchor="#srv-protect",
         title="Password protect a PDF — free encryption",
         h1="Password protect a PDF",
         desc="Encrypt a PDF so a password is required to open it. Free while in beta.",
         what="Adds an open-password to your document.",
         steps=["Choose a PDF.", "Type the password you want.", "Download the protected file."],
         faq=[("What if I forget the password?",
               "We cannot recover it. Keep it somewhere safe."),
              ("Which encryption is used?", "Standard PDF encryption, applied server-side.")]),
    dict(slug="repair-pdf", anchor="#srv-repair",
         title="Repair a corrupted PDF — free",
         h1="Repair a PDF that won't open",
         desc="Rebuild the internal structure of a damaged PDF and try to recover it. Free while in beta.",
         what="Reads what it can and writes a clean file back out.",
         steps=["Choose the damaged PDF.", "Press Try repair.", "Download the rebuilt file."],
         faq=[("Will it always work?",
               "No. If the data is genuinely gone, nothing can bring it back. It costs you one click to find out."),
              ("Is the original changed?", "No. You get a new file.")]),
    dict(slug="office-to-pdf", anchor="#srv-office",
         title="Word, Excel, PowerPoint to PDF — free converter",
         h1="Convert Office documents to PDF",
         desc="Convert .docx, .xlsx, .pptx, .doc, .hwp and .odt files to PDF. Free while in beta, no sign-up.",
         what="Renders your document server-side and hands back a PDF.",
         steps=["Choose your document.", "Press Convert to PDF.", "Download."],
         faq=[("Does it handle HWP?", "Yes — Korean HWP files are supported."),
              ("Will the layout shift?", "Usually not, but complex layouts can differ slightly from the original application.")]),
]
